/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-card-text.component';
const styles_UICardTextComponent:any[] = ([] as any[]);
export const RenderType_UICardTextComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UICardTextComponent,
  data: {}
}
);
export function View_UICardTextComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(null as any));
}
function View_UICardTextComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-card-text',([] as any[]),(null as any),(null as any),(null as any),View_UICardTextComponent_0,RenderType_UICardTextComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UICardTextComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UICardTextComponentNgFactory:import0.ComponentFactory<import1.UICardTextComponent> = import0.ɵccf('ui-card-text',import1.UICardTextComponent,View_UICardTextComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jYXJkL3VpLWNhcmQtdGV4dC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jYXJkL3VpLWNhcmQtdGV4dC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWNhcmQvdWktY2FyZC10ZXh0LmNvbXBvbmVudC50cy5VSUNhcmRUZXh0Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWNhcmQvdWktY2FyZC10ZXh0LmNvbXBvbmVudC50cy5VSUNhcmRUZXh0Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG5cdFx0PGRpdiBjbGFzcz1cImNhcmQtdGV4dFwiPlxuXHRcdFx0PG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuXHRcdDwvZGl2PlxuXHQiLCI8dWktY2FyZC10ZXh0PjwvdWktY2FyZC10ZXh0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNFO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBdUI7Z0JBQ3RCO0lBQXlCO0lBQ3BCOzs7Ozs7SUNIUjtnQkFBQTs7OzsifQ==
