/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-card-block.component';
const styles_UICardBlockComponent:any[] = ([] as any[]);
export const RenderType_UICardBlockComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UICardBlockComponent,
  data: {}
}
);
export function View_UICardBlockComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'card-block'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(null as any));
}
function View_UICardBlockComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-card-block',([] as any[]),(null as any),(null as any),(null as any),View_UICardBlockComponent_0,RenderType_UICardBlockComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UICardBlockComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UICardBlockComponentNgFactory:import0.ComponentFactory<import1.UICardBlockComponent> = import0.ɵccf('ui-card-block',import1.UICardBlockComponent,View_UICardBlockComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jYXJkL3VpLWNhcmQtYmxvY2suY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktY2FyZC91aS1jYXJkLWJsb2NrLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktY2FyZC91aS1jYXJkLWJsb2NrLmNvbXBvbmVudC50cy5VSUNhcmRCbG9ja0NvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jYXJkL3VpLWNhcmQtYmxvY2suY29tcG9uZW50LnRzLlVJQ2FyZEJsb2NrQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG5cdFx0PGRpdiBjbGFzcz1cImNhcmQtYmxvY2tcIj5cblx0XHRcdDxuZy1jb250ZW50PjwvbmctY29udGVudD5cblx0XHQ8L2Rpdj5cblx0IiwiPHVpLWNhcmQtYmxvY2s+PC91aS1jYXJkLWJsb2NrPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNFO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0I7Z0JBQ3ZCO0lBQXlCO0lBQ3BCOzs7Ozs7SUNIUjtnQkFBQTs7OzsifQ==
