/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-card.component';
const styles_UICardComponent:any[] = ['.lift[_ngcontent-%COMP%] { \n			box-shadow: 5px 5px 5px #888888;\n		}'];
export const RenderType_UICardComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_UICardComponent,
  data: {}
}
);
export function View_UICardComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',([] as any[]),[[
        8,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.UICardComponent = v.component;
    const currVal_0:any = co.classBinding;
    ck(v,1,0,currVal_0);
  });
}
function View_UICardComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-card',([] as any[]),(null as any),(null as any),(null as any),View_UICardComponent_0,RenderType_UICardComponent)),
    import0.ɵdid(319488,(null as any),0,import1.UICardComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UICardComponentNgFactory:import0.ComponentFactory<import1.UICardComponent> = import0.ɵccf('ui-card',import1.UICardComponent,View_UICardComponent_Host_0,{
  outline: 'outline',
  theme: 'theme',
  lift: 'lift'
}
,{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jYXJkL3VpLWNhcmQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktY2FyZC91aS1jYXJkLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktY2FyZC91aS1jYXJkLmNvbXBvbmVudC50cy5VSUNhcmRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktY2FyZC91aS1jYXJkLmNvbXBvbmVudC50cy5VSUNhcmRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8ZGl2IFtjbGFzc109XCJjbGFzc0JpbmRpbmdcIj5cblx0XHRcdDxuZy1jb250ZW50PjwvbmctY29udGVudD5cblx0XHQ8L2Rpdj5cblx0IiwiPHVpLWNhcmQ+PC91aS1jYXJkPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNFO1FBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUE0QjtnQkFDM0I7SUFBeUI7SUFDcEI7Ozs7SUFGRDtJQUFMLFNBQUssU0FBTDs7Ozs7SUNERjtnQkFBQTs7O0lBQUE7Ozs7Ozs7OyJ9
