var index = require('./dist/index')
exports.Angular2UIModule = index.Angular2UIModule;
//exports.UIAddonComponent = index.UIAddonComponent;
//exports.UIButtonComponent = index.UIButtonComponent;
//exports.UIButtonGroupComponent = index.UIButtonGroupComponent;
//exports.UICardComponent = index.UICardComponent;
//exports.UICardTextComponent = index.UICardTextComponent;
//exports.UICardTitleComponent = index.UICardTitleComponent;
//exports.UICardBlockComponent = index.UICardBlockComponent;
//exports.UIColumnComponent = index.UIColumnComponent;
//exports.UIContainerComponent = index.UIContainerComponent;
//exports.UIListComponent = index.UIListComponent;
//exports.UINavbarComponent = index.UINavbarComponent;
//exports.UINavbarHeaderComponent = index.UINavbarHeaderComponent;
//exports.UIRowComponent = index.UIRowComponent;
//exports.UIIconComponent = index.UIIconComponent;
//exports.UIInputComponent = index.UIInputComponent;
//exports.UIInputGroupComponent = index.UIInputGroupComponent;
//exports.UIAddonComponent = index.UIAddonComponent;
//exports.UIPasswordComponent = index.UIPasswordComponent;
//exports.UIFormComponent = index.UIFormComponent;
//exports.UITypeaheadComponent = index.UITypeaheadComponent;
//exports.UILoaderCircularComponent = index.UILoaderCircularComponent;

exports.UIModalService = index.UIModalService;
exports.UIResourceCacheService = index.UIResourceCacheService;