export { 
	Angular2UIModule,
	UI_COMPONENTS,
	UIAddonComponent,
	UIButtonComponent, 
	UIButtonGroupComponent,
	UICardBlockComponent,
	UICardComponent,
	UICardTextComponent,
	UICardTitleComponent,
	UIColumnComponent,
	UIContainerComponent,
	UIFormComponent,
	UIIconComponent,
	UIInputComponent,
	UIInputGroupComponent,
	UIListComponent,
	UILoaderCircularComponent,
	UINavbarComponent,
	UINavbarHeaderComponent,
	UIPasswordComponent,
	UIRowComponent,
	UITypeaheadComponent,
	UIModalService,
	UIResourceCacheService
} from './dist/index';
