/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/forms';
import * as import2 from './ui-form.component';
const styles_UIFormComponent:any[] = ([] as any[]);
export const RenderType_UIFormComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIFormComponent,
  data: {}
}
);
export function View_UIFormComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),7,'form',[[
        'novalidate',
        ''
      ]
    ],[
      [
        2,
        'form-inline',
        (null as any)
      ]
      ,
      [
        2,
        'ng-untouched',
        (null as any)
      ]
      ,
      [
        2,
        'ng-touched',
        (null as any)
      ]
      ,
      [
        2,
        'ng-pristine',
        (null as any)
      ]
      ,
      [
        2,
        'ng-dirty',
        (null as any)
      ]
      ,
      [
        2,
        'ng-valid',
        (null as any)
      ]
      ,
      [
        2,
        'ng-invalid',
        (null as any)
      ]
      ,
      [
        2,
        'ng-pending',
        (null as any)
      ]

    ]
    ,[
      [
        (null as any),
        'submit'
      ]
      ,
      [
        (null as any),
        'reset'
      ]

    ]
    ,(v,en,$event) => {
      var ad:boolean = true;
      if (('submit' === en)) {
        const pd_0:any = ((<any>import0.ɵnov(v,3).onSubmit($event)) !== false);
        ad = (pd_0 && ad);
      }
      if (('reset' === en)) {
        const pd_1:any = ((<any>import0.ɵnov(v,3).onReset()) !== false);
        ad = (pd_1 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    import0.ɵdid(8192,(null as any),0,import1.ɵbf,([] as any[]),(null as any),(null as any)),
    import0.ɵdid(8192,(null as any),0,import1.NgForm,[
      [
        8,
        (null as any)
      ]
      ,
      [
        8,
        (null as any)
      ]

    ]
    ,(null as any),(null as any)),
    import0.ɵprd(1024,(null as any),import1.ControlContainer,(null as any),[import1.NgForm]),
    import0.ɵdid(8192,(null as any),0,import1.NgControlStatusGroup,[import1.ControlContainer],(null as any),(null as any)),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.UIFormComponent = v.component;
    const currVal_0:any = co.inline;
    const currVal_1:any = import0.ɵnov(v,5).ngClassUntouched;
    const currVal_2:any = import0.ɵnov(v,5).ngClassTouched;
    const currVal_3:any = import0.ɵnov(v,5).ngClassPristine;
    const currVal_4:any = import0.ɵnov(v,5).ngClassDirty;
    const currVal_5:any = import0.ɵnov(v,5).ngClassValid;
    const currVal_6:any = import0.ɵnov(v,5).ngClassInvalid;
    const currVal_7:any = import0.ɵnov(v,5).ngClassPending;
    ck(v,1,0,currVal_0,currVal_1,currVal_2,currVal_3,currVal_4,currVal_5,currVal_6,currVal_7);
  });
}
function View_UIFormComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-form',([] as any[]),(null as any),(null as any),(null as any),View_UIFormComponent_0,RenderType_UIFormComponent)),
    import0.ɵdid(24576,(null as any),0,import2.UIFormComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UIFormComponentNgFactory:import0.ComponentFactory<import2.UIFormComponent> = import0.ɵccf('ui-form',import2.UIFormComponent,View_UIFormComponent_Host_0,{inline: 'inline'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1mb3JtL3VpLWZvcm0uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktZm9ybS91aS1mb3JtLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktZm9ybS91aS1mb3JtLmNvbXBvbmVudC50cy5VSUZvcm1Db21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktZm9ybS91aS1mb3JtLmNvbXBvbmVudC50cy5VSUZvcm1Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8Zm9ybSBbY2xhc3MuZm9ybS1pbmxpbmVdPVwiaW5saW5lXCI+XG5cdFx0XHQ8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG5cdFx0PC9mb3JtPlxuXHQiLCI8dWktZm9ybT48L3VpLWZvcm0+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNFO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtNQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0tBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtNQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtJQUFBO2dCQUFBO2dCQUFBO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtnQkFBQTtnQkFBQTtJQUFtQztnQkFDbEM7SUFBeUI7SUFDbkI7Ozs7SUFGRDtJQUFOO0lBQUE7SUFBQTtJQUFBO0lBQUE7SUFBQTtJQUFBO0lBQUEsU0FBTSxVQUFOLHFFQUFBOzs7OztJQ0RGO2dCQUFBOzs7OyJ9
