/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-loader-circular.component';
const styles_UILoaderCircularComponent:any[] = ['body[_ngcontent-%COMP%] {\n		  background-color: #eee;\n		}\n\n		.ui-showbox[_ngcontent-%COMP%] {\n		  top: 0;\n		  bottom: 0;\n		  left: 0;\n		  right: 0;\n		}\n\n		.ui-loader[_ngcontent-%COMP%] {\n		  position: relative;\n		  margin: 0px auto;\n		  width: 100px;\n		}\n\n		.ui-loader[_ngcontent-%COMP%]:before {\n		  content: \'\';\n		  display: block;\n		  padding-top: 100%;\n		}\n\n		.circular[_ngcontent-%COMP%] {\n		  -webkit-animation: rotate 2s linear infinite;\n		          animation: rotate 2s linear infinite;\n		  height: 100%;\n		  -webkit-transform-origin: center center;\n		          transform-origin: center center;\n		  width: 100%;\n		  position: absolute;\n		  top: 0;\n		  bottom: 0;\n		  left: 0;\n		  right: 0;\n		  margin: auto;\n		}\n\n		.path[_ngcontent-%COMP%] {\n		  stroke-dasharray: 1, 200;\n		  stroke-dashoffset: 0;\n		  -webkit-animation: dash 1.5s ease-in-out infinite, color 6s ease-in-out infinite;\n		          animation: dash 1.5s ease-in-out infinite, color 6s ease-in-out infinite;\n		  stroke-linecap: round;\n		}\n\n		@-webkit-keyframes rotate {\n		  100% {\n		    -webkit-transform: rotate(360deg);\n		            transform: rotate(360deg);\n		  }\n		}\n\n		@keyframes rotate {\n		  100% {\n		    -webkit-transform: rotate(360deg);\n		            transform: rotate(360deg);\n		  }\n		}\n		@-webkit-keyframes dash {\n		  0% {\n		    stroke-dasharray: 1, 200;\n		    stroke-dashoffset: 0;\n		  }\n		  50% {\n		    stroke-dasharray: 89, 200;\n		    stroke-dashoffset: -35px;\n		  }\n		  100% {\n		    stroke-dasharray: 89, 200;\n		    stroke-dashoffset: -124px;\n		  }\n		}\n		@keyframes dash {\n		  0% {\n		    stroke-dasharray: 1, 200;\n		    stroke-dashoffset: 0;\n		  }\n		  50% {\n		    stroke-dasharray: 89, 200;\n		    stroke-dashoffset: -35px;\n		  }\n		  100% {\n		    stroke-dasharray: 89, 200;\n		    stroke-dashoffset: -124px;\n		  }\n		}'];
export const RenderType_UILoaderCircularComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_UILoaderCircularComponent,
  data: {}
}
);
export function View_UILoaderCircularComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n	'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),9,'div',[[
        'class',
        'ui-showbox'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n  		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),6,'div',[[
        'class',
        'ui-loader'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),3,':svg:svg',[
      [
        'class',
        'circular'
      ]
      ,
      [
        'viewBox',
        '25 25 50 50'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      			'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),0,':svg:circle',[
      [
        'class',
        'path'
      ]
      ,
      [
        'cx',
        '50'
      ]
      ,
      [
        'cy',
        '50'
      ]
      ,
      [
        'fill',
        'none'
      ]
      ,
      [
        'r',
        '20'
      ]
      ,
      [
        'stroke-miterlimit',
        '10'
      ]
      ,
      [
        'stroke-width',
        '2'
      ]

    ]
      ,[[
        4,
        'stroke',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    		'])),
    (l()(),import0.ɵted((null as any),['\n    	'])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n  \n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.UILoaderCircularComponent = v.component;
    const currVal_0:any = co.color;
    ck(v,7,0,currVal_0);
  });
}
function View_UILoaderCircularComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-loader-circular',([] as any[]),(null as any),(null as any),(null as any),View_UILoaderCircularComponent_0,RenderType_UILoaderCircularComponent)),
    import0.ɵdid(57344,(null as any),0,import1.UILoaderCircularComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UILoaderCircularComponentNgFactory:import0.ComponentFactory<import1.UILoaderCircularComponent> = import0.ɵccf('ui-loader-circular',import1.UILoaderCircularComponent,View_UILoaderCircularComponent_Host_0,{color: 'color'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1sb2FkZXItY2lyY3VsYXIvdWktbG9hZGVyLWNpcmN1bGFyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWxvYWRlci1jaXJjdWxhci91aS1sb2FkZXItY2lyY3VsYXIuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1sb2FkZXItY2lyY3VsYXIvdWktbG9hZGVyLWNpcmN1bGFyLmNvbXBvbmVudC50cy5VSUxvYWRlckNpcmN1bGFyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWxvYWRlci1jaXJjdWxhci91aS1sb2FkZXItY2lyY3VsYXIuY29tcG9uZW50LnRzLlVJTG9hZGVyQ2lyY3VsYXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0PGRpdiBjbGFzcz1cInVpLXNob3dib3hcIj5cbiAgXHRcdDxkaXYgY2xhc3M9XCJ1aS1sb2FkZXJcIj5cblx0XHRcdDxzdmcgY2xhc3M9XCJjaXJjdWxhclwiIHZpZXdCb3g9XCIyNSAyNSA1MCA1MFwiPlxuICAgICAgXHRcdFx0PGNpcmNsZSBjbGFzcz1cInBhdGhcIiBjeD1cIjUwXCIgY3k9XCI1MFwiIHI9XCIyMFwiIGZpbGw9XCJub25lXCIgc3Ryb2tlLXdpZHRoPVwiMlwiIHN0cm9rZS1taXRlcmxpbWl0PVwiMTBcIiBbc3R5bGUuc3Ryb2tlXT1cImNvbG9yXCIvPlxuICAgIFx0XHQ8L3N2Zz5cbiAgICBcdDwvZGl2PlxuICAgIDwvZGl2PlxuICBcblx0IiwiPHVpLWxvYWRlci1jaXJjdWxhcj48L3VpLWxvYWRlci1jaXJjdWxhcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDQztRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXdCO01BQ3JCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBdUI7SUFDeEI7TUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBQTRDO0lBQ3RDO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7T0FBQTtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0g7SUFDckg7SUFDRDtJQUNEOzs7O0lBSCtGO0lBQWhHLFNBQWdHLFNBQWhHOzs7OztJQ0pUO2dCQUFBOzs7SUFBQTs7OyJ9
