/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ui-navbar-header.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_UINavbarHeaderComponent_Host:import0.RenderComponentType = (null as any);
class _View_UINavbarHeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UINavbarHeaderComponent_0_4:import3.UINavbarHeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UINavbarHeaderComponent_Host0,renderType_UINavbarHeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ui-navbar-header',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UINavbarHeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UINavbarHeaderComponent_0_4 = new import3.UINavbarHeaderComponent();
    this._appEl_0.initComponent(this._UINavbarHeaderComponent_0_4,[],compView_0);
    compView_0.create(this._UINavbarHeaderComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UINavbarHeaderComponent) && (0 === requestNodeIndex))) { return this._UINavbarHeaderComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_UINavbarHeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UINavbarHeaderComponent_Host === (null as any))) { (renderType_UINavbarHeaderComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_UINavbarHeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UINavbarHeaderComponentNgFactory:import9.ComponentFactory<import3.UINavbarHeaderComponent> = new import9.ComponentFactory<import3.UINavbarHeaderComponent>('ui-navbar-header',viewFactory_UINavbarHeaderComponent_Host0,import3.UINavbarHeaderComponent);
const styles_UINavbarHeaderComponent:any[] = [];
var renderType_UINavbarHeaderComponent:import0.RenderComponentType = (null as any);
class _View_UINavbarHeaderComponent0 extends import1.AppView<import3.UINavbarHeaderComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UINavbarHeaderComponent0,renderType_UINavbarHeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n		',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','navbar-header');
    this._text_2 = this.renderer.createText(this._el_1,'\n			',(null as any));
    this.renderer.projectNodes(this._el_1,import4.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_3 = this.renderer.createText(this._el_1,'\n		',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n	',(null as any));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_UINavbarHeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UINavbarHeaderComponent> {
  if ((renderType_UINavbarHeaderComponent === (null as any))) { (renderType_UINavbarHeaderComponent = viewUtils.createRenderComponentType('D:/Code/angular2-ui/src/components/ui-navbar/ui-navbar-header.component.ts class UINavbarHeaderComponent - inline template',1,import8.ViewEncapsulation.None,styles_UINavbarHeaderComponent,{})); }
  return new _View_UINavbarHeaderComponent0(viewUtils,parentInjector,declarationEl);
}