/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-navbar-header.component';
const styles_UINavbarHeaderComponent:any[] = ([] as any[]);
export const RenderType_UINavbarHeaderComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UINavbarHeaderComponent,
  data: {}
}
);
export function View_UINavbarHeaderComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'navbar-header'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(null as any));
}
function View_UINavbarHeaderComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-navbar-header',([] as any[]),(null as any),(null as any),(null as any),View_UINavbarHeaderComponent_0,RenderType_UINavbarHeaderComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UINavbarHeaderComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UINavbarHeaderComponentNgFactory:import0.ComponentFactory<import1.UINavbarHeaderComponent> = import0.ɵccf('ui-navbar-header',import1.UINavbarHeaderComponent,View_UINavbarHeaderComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1uYXZiYXIvdWktbmF2YmFyLWhlYWRlci5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1uYXZiYXIvdWktbmF2YmFyLWhlYWRlci5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLW5hdmJhci91aS1uYXZiYXItaGVhZGVyLmNvbXBvbmVudC50cy5VSU5hdmJhckhlYWRlckNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1uYXZiYXIvdWktbmF2YmFyLWhlYWRlci5jb21wb25lbnQudHMuVUlOYXZiYXJIZWFkZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8ZGl2IGNsYXNzPVwibmF2YmFyLWhlYWRlclwiPlxuXHRcdFx0PG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuXHRcdDwvZGl2PlxuXHQiLCI8dWktbmF2YmFyLWhlYWRlcj48L3VpLW5hdmJhci1oZWFkZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO01BQ0U7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyQjtnQkFDMUI7SUFBeUI7SUFDcEI7Ozs7OztJQ0hSO2dCQUFBOzs7OyJ9
