/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-navbar.component';
const styles_UINavbarComponent:any[] = ['nav[_ngcontent-%COMP%] { \n			height: 50px;\n			box-shadow: 5px 5px 15px #888888;\n			margin-bottom: 100px;\n		}'];
export const RenderType_UINavbarComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_UINavbarComponent,
  data: {}
}
);
export function View_UINavbarComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'nav',[[
        'class',
        'navbar navbar-default navbar-fixed-top navbar-light bg-faded'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(null as any));
}
function View_UINavbarComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-navbar',([] as any[]),(null as any),(null as any),(null as any),View_UINavbarComponent_0,RenderType_UINavbarComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UINavbarComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UINavbarComponentNgFactory:import0.ComponentFactory<import1.UINavbarComponent> = import0.ɵccf('ui-navbar',import1.UINavbarComponent,View_UINavbarComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1uYXZiYXIvdWktbmF2YmFyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLW5hdmJhci91aS1uYXZiYXIuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1uYXZiYXIvdWktbmF2YmFyLmNvbXBvbmVudC50cy5VSU5hdmJhckNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1uYXZiYXIvdWktbmF2YmFyLmNvbXBvbmVudC50cy5VSU5hdmJhckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuXHRcdDxuYXYgY2xhc3M9XCJuYXZiYXIgbmF2YmFyLWRlZmF1bHQgbmF2YmFyLWZpeGVkLXRvcCBuYXZiYXItbGlnaHQgYmctZmFkZWRcIj5cblx0XHRcdDxuZy1jb250ZW50PjwvbmctY29udGVudD5cblx0XHQ8L25hdj5cblx0IiwiPHVpLW5hdmJhcj48L3VpLW5hdmJhcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDRTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQTBFO2dCQUN6RTtJQUF5QjtJQUNwQjs7Ozs7O0lDSFI7Z0JBQUE7Ozs7In0=
