/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ui-navbar.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_UINavbarComponent_Host:import0.RenderComponentType = (null as any);
class _View_UINavbarComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UINavbarComponent_0_4:import3.UINavbarComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UINavbarComponent_Host0,renderType_UINavbarComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ui-navbar',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UINavbarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UINavbarComponent_0_4 = new import3.UINavbarComponent();
    this._appEl_0.initComponent(this._UINavbarComponent_0_4,[],compView_0);
    compView_0.create(this._UINavbarComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UINavbarComponent) && (0 === requestNodeIndex))) { return this._UINavbarComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_UINavbarComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UINavbarComponent_Host === (null as any))) { (renderType_UINavbarComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_UINavbarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UINavbarComponentNgFactory:import9.ComponentFactory<import3.UINavbarComponent> = new import9.ComponentFactory<import3.UINavbarComponent>('ui-navbar',viewFactory_UINavbarComponent_Host0,import3.UINavbarComponent);
const styles_UINavbarComponent:any[] = ['nav[_ngcontent-%COMP%] { \n			height: 50px;\n			box-shadow: 5px 5px 15px #888888;\n			margin-bottom: 100px;\n		}'];
var renderType_UINavbarComponent:import0.RenderComponentType = (null as any);
class _View_UINavbarComponent0 extends import1.AppView<import3.UINavbarComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UINavbarComponent0,renderType_UINavbarComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n		',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'nav',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','navbar navbar-default navbar-fixed-top navbar-light bg-faded');
    this._text_2 = this.renderer.createText(this._el_1,'\n			',(null as any));
    this.renderer.projectNodes(this._el_1,import4.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_3 = this.renderer.createText(this._el_1,'\n		',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n	',(null as any));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_UINavbarComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UINavbarComponent> {
  if ((renderType_UINavbarComponent === (null as any))) { (renderType_UINavbarComponent = viewUtils.createRenderComponentType('D:/Code/angular2-ui/src/components/ui-navbar/ui-navbar.component.ts class UINavbarComponent - inline template',1,import8.ViewEncapsulation.Emulated,styles_UINavbarComponent,{})); }
  return new _View_UINavbarComponent0(viewUtils,parentInjector,declarationEl);
}