/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from './ui-list.component';
const styles_UIListComponent:any[] = ([] as any[]);
export const RenderType_UIListComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIListComponent,
  data: {}
}
);
function View_UIListComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'a',[[
        'class',
        'list-group-item'
      ]
      ],[[
        2,
        'active',
        (null as any)
      ]
      ],[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:any = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.selected_fn(v.context.$implicit)) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    const currVal_0:any = v.context.$implicit.active();
    ck(v,0,0,currVal_0);
    const currVal_1:any = v.context.$implicit.display();
    ck(v,1,0,currVal_1);
  });
}
export function View_UIListComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'list-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_UIListComponent_1)),
    import0.ɵdid(401408,(null as any),0,import1.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(ck,v) => {
    var co:import2.UIListComponent = v.component;
    const currVal_0:any = co.viewModels;
    ck(v,4,0,currVal_0);
  },(null as any));
}
function View_UIListComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-list',([] as any[]),(null as any),(null as any),(null as any),View_UIListComponent_0,RenderType_UIListComponent)),
    import0.ɵdid(319488,(null as any),0,import2.UIListComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UIListComponentNgFactory:import0.ComponentFactory<import2.UIListComponent> = import0.ɵccf('ui-list',import2.UIListComponent,View_UIListComponent_Host_0,{
  items: 'items',
  display_fn: 'display-fn',
  selected_fn: 'selected-fn',
  active_fn: 'active-fn'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1saXN0L3VpLWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktbGlzdC91aS1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktbGlzdC91aS1saXN0LmNvbXBvbmVudC50cy5VSUxpc3RDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktbGlzdC91aS1saXN0LmNvbXBvbmVudC50cy5VSUxpc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8ZGl2IGNsYXNzPVwibGlzdC1ncm91cFwiPlxuXHRcdFx0PGEgY2xhc3M9XCJsaXN0LWdyb3VwLWl0ZW1cIiBbY2xhc3MuYWN0aXZlXT1cIml0ZW0uYWN0aXZlKClcIiAqbmdGb3I9XCJsZXQgaXRlbSBvZiB2aWV3TW9kZWxzXCIgKGNsaWNrKT1cInNlbGVjdGVkX2ZuKGl0ZW0pXCI+e3tpdGVtLmRpc3BsYXkoKX19PC9hPlxuXHRcdDwvZGl2PlxuXHQiLCI8dWktbGlzdD48L3VpLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7TUNFRztRQUFBO1FBQUE7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7TUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7TUFBQTtNQUEwRjtRQUFBO1FBQUE7TUFBQTtNQUExRjtJQUFBO0lBQXNIO01BQUE7TUFBQTtJQUFBO0lBQUE7OztJQUEzRjtJQUEzQixTQUEyQixTQUEzQjtJQUFzSDtJQUFBOzs7OztJQUZ6SDtNQUNFO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0I7SUFDdkI7Z0JBQUE7Ozs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBNEk7SUFDdkk7Ozs7SUFEcUQ7SUFBMUQsU0FBMEQsU0FBMUQ7Ozs7O0lDRkg7Z0JBQUE7OztJQUFBOzs7Ozs7Ozs7In0=
