/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-button.component';
const styles_UIButtonComponent:any[] = ([] as any[]);
export const RenderType_UIButtonComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIButtonComponent,
  data: {}
}
);
export function View_UIButtonComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'button',([] as any[]),[[
        8,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.UIButtonComponent = v.component;
    const currVal_0:any = co.classBinding;
    ck(v,1,0,currVal_0);
  });
}
function View_UIButtonComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-button',([] as any[]),(null as any),(null as any),(null as any),View_UIButtonComponent_0,RenderType_UIButtonComponent)),
    import0.ɵdid(57344,(null as any),0,import1.UIButtonComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UIButtonComponentNgFactory:import0.ComponentFactory<import1.UIButtonComponent> = import0.ɵccf('ui-button',import1.UIButtonComponent,View_UIButtonComponent_Host_0,{
  theme: 'theme',
  outline: 'outline',
  block: 'block'
}
,{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1idXR0b24vdWktYnV0dG9uLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWJ1dHRvbi91aS1idXR0b24uY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1idXR0b24vdWktYnV0dG9uLmNvbXBvbmVudC50cy5VSUJ1dHRvbkNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1idXR0b24vdWktYnV0dG9uLmNvbXBvbmVudC50cy5VSUJ1dHRvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuXHRcdDxidXR0b24gW2NsYXNzXT1cImNsYXNzQmluZGluZ1wiPlxuXHRcdFx0PG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuXHRcdDwvYnV0dG9uPlxuXHQiLCI8dWktYnV0dG9uPjwvdWktYnV0dG9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNFO1FBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUErQjtnQkFDOUI7SUFBeUI7SUFDakI7Ozs7SUFGRDtJQUFSLFNBQVEsU0FBUjs7Ozs7SUNERjtnQkFBQTs7O0lBQUE7Ozs7Ozs7OyJ9
