/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ui-button-group.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_UIButtonGroupComponent_Host:import0.RenderComponentType = (null as any);
class _View_UIButtonGroupComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UIButtonGroupComponent_0_4:import3.UIButtonGroupComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UIButtonGroupComponent_Host0,renderType_UIButtonGroupComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ui-button-group',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UIButtonGroupComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UIButtonGroupComponent_0_4 = new import3.UIButtonGroupComponent();
    this._appEl_0.initComponent(this._UIButtonGroupComponent_0_4,[],compView_0);
    compView_0.create(this._UIButtonGroupComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UIButtonGroupComponent) && (0 === requestNodeIndex))) { return this._UIButtonGroupComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_UIButtonGroupComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UIButtonGroupComponent_Host === (null as any))) { (renderType_UIButtonGroupComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_UIButtonGroupComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UIButtonGroupComponentNgFactory:import9.ComponentFactory<import3.UIButtonGroupComponent> = new import9.ComponentFactory<import3.UIButtonGroupComponent>('ui-button-group',viewFactory_UIButtonGroupComponent_Host0,import3.UIButtonGroupComponent);
const styles_UIButtonGroupComponent:any[] = [];
var renderType_UIButtonGroupComponent:import0.RenderComponentType = (null as any);
class _View_UIButtonGroupComponent0 extends import1.AppView<import3.UIButtonGroupComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UIButtonGroupComponent0,renderType_UIButtonGroupComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n		',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','btn-group');
    this._text_2 = this.renderer.createText(this._el_1,'\n			',(null as any));
    this.renderer.projectNodes(this._el_1,import4.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_3 = this.renderer.createText(this._el_1,'\n		',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n	',(null as any));
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._text_4
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_UIButtonGroupComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UIButtonGroupComponent> {
  if ((renderType_UIButtonGroupComponent === (null as any))) { (renderType_UIButtonGroupComponent = viewUtils.createRenderComponentType('D:/Code/angular2-ui/src/components/ui-button/ui-button-group.component.ts class UIButtonGroupComponent - inline template',1,import8.ViewEncapsulation.None,styles_UIButtonGroupComponent,{})); }
  return new _View_UIButtonGroupComponent0(viewUtils,parentInjector,declarationEl);
}