/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-button-group.component';
const styles_UIButtonGroupComponent:any[] = ([] as any[]);
export const RenderType_UIButtonGroupComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIButtonGroupComponent,
  data: {}
}
);
export function View_UIButtonGroupComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'btn-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(null as any));
}
function View_UIButtonGroupComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-button-group',([] as any[]),(null as any),(null as any),(null as any),View_UIButtonGroupComponent_0,RenderType_UIButtonGroupComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UIButtonGroupComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UIButtonGroupComponentNgFactory:import0.ComponentFactory<import1.UIButtonGroupComponent> = import0.ɵccf('ui-button-group',import1.UIButtonGroupComponent,View_UIButtonGroupComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1idXR0b24vdWktYnV0dG9uLWdyb3VwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWJ1dHRvbi91aS1idXR0b24tZ3JvdXAuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1idXR0b24vdWktYnV0dG9uLWdyb3VwLmNvbXBvbmVudC50cy5VSUJ1dHRvbkdyb3VwQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWJ1dHRvbi91aS1idXR0b24tZ3JvdXAuY29tcG9uZW50LnRzLlVJQnV0dG9uR3JvdXBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8ZGl2IGNsYXNzPVwiYnRuLWdyb3VwXCI+XG5cdFx0XHQ8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG5cdFx0PC9kaXY+XG5cdCIsIjx1aS1idXR0b24tZ3JvdXA+PC91aS1idXR0b24tZ3JvdXA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO01BQ0U7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUF1QjtnQkFDdEI7SUFBeUI7SUFDcEI7Ozs7OztJQ0hSO2dCQUFBOzs7OyJ9
