/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-container.component';
const styles_UIContainerComponent:any[] = ([] as any[]);
export const RenderType_UIContainerComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIContainerComponent,
  data: {}
}
);
export function View_UIContainerComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',([] as any[]),[
      [
        2,
        'container',
        (null as any)
      ]
      ,
      [
        2,
        'container-fluid',
        (null as any)
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.UIContainerComponent = v.component;
    const currVal_0:boolean = !co.fluid;
    const currVal_1:any = co.fluid;
    ck(v,1,0,currVal_0,currVal_1);
  });
}
function View_UIContainerComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-container',([] as any[]),(null as any),(null as any),(null as any),View_UIContainerComponent_0,RenderType_UIContainerComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UIContainerComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UIContainerComponentNgFactory:import0.ComponentFactory<import1.UIContainerComponent> = import0.ɵccf('ui-container',import1.UIContainerComponent,View_UIContainerComponent_Host_0,{fluid: 'fluid'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jb250YWluZXIvdWktY29udGFpbmVyLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWNvbnRhaW5lci91aS1jb250YWluZXIuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jb250YWluZXIvdWktY29udGFpbmVyLmNvbXBvbmVudC50cy5VSUNvbnRhaW5lckNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jb250YWluZXIvdWktY29udGFpbmVyLmNvbXBvbmVudC50cy5VSUNvbnRhaW5lckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuXHRcdDxkaXYgW2NsYXNzLmNvbnRhaW5lcl09XCIhZmx1aWRcIiBbY2xhc3MuY29udGFpbmVyLWZsdWlkXT1cImZsdWlkXCI+XG5cdFx0XHQ8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG5cdFx0PC9kaXY+XG5cdCIsIjx1aS1jb250YWluZXI+PC91aS1jb250YWluZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0U7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUFnRTtnQkFDL0Q7SUFBeUI7SUFDcEI7Ozs7SUFGRDtJQUEyQjtJQUFoQyxTQUFLLFVBQTJCLFNBQWhDOzs7OztJQ0RGO2dCQUFBOzs7OyJ9
