/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './index';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import8 from '@angular/http/src/backends/browser_xhr';
import * as import9 from '@angular/http/src/base_response_options';
import * as import10 from '@angular/http/src/backends/xhr_backend';
import * as import11 from '@angular/http/src/base_request_options';
import * as import12 from './services/ui-modal.service';
import * as import13 from './services/ui-resource-cache.service';
import * as import14 from '@angular/core/src/di/injector';
import * as import15 from '@angular/core/src/i18n/tokens';
import * as import16 from '@angular/http/src/interfaces';
import * as import17 from '@angular/http/src/http';
class Angular2UIModuleInjector extends import0.NgModuleInjector<import1.Angular2UIModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _HttpModule_3:import5.HttpModule;
  _Angular2UIModule_4:import1.Angular2UIModule;
  __LOCALE_ID_5:any;
  __NgLocalization_6:import6.NgLocaleLocalization;
  __RadioControlRegistry_7:import7.RadioControlRegistry;
  __BrowserXhr_8:import8.BrowserXhr;
  __ResponseOptions_9:import9.BaseResponseOptions;
  __XSRFStrategy_10:any;
  __XHRBackend_11:import10.XHRBackend;
  __RequestOptions_12:import11.BaseRequestOptions;
  __Http_13:any;
  __UIModalService_14:import12.UIModalService;
  __UIResourceCacheService_15:import13.UIResourceCacheService;
  __TRANSLATIONS_FORMAT_16:any;
  constructor(parent:import14.Injector) {
    super(parent,[],[]);
  }
  get _LOCALE_ID_5():any {
    if ((this.__LOCALE_ID_5 == (null as any))) { (this.__LOCALE_ID_5 = (null as any)); }
    return this.__LOCALE_ID_5;
  }
  get _NgLocalization_6():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == (null as any))) { (this.__NgLocalization_6 = new import6.NgLocaleLocalization(this._LOCALE_ID_5)); }
    return this.__NgLocalization_6;
  }
  get _RadioControlRegistry_7():import7.RadioControlRegistry {
    if ((this.__RadioControlRegistry_7 == (null as any))) { (this.__RadioControlRegistry_7 = new import7.RadioControlRegistry()); }
    return this.__RadioControlRegistry_7;
  }
  get _BrowserXhr_8():import8.BrowserXhr {
    if ((this.__BrowserXhr_8 == (null as any))) { (this.__BrowserXhr_8 = new import8.BrowserXhr()); }
    return this.__BrowserXhr_8;
  }
  get _ResponseOptions_9():import9.BaseResponseOptions {
    if ((this.__ResponseOptions_9 == (null as any))) { (this.__ResponseOptions_9 = new import9.BaseResponseOptions()); }
    return this.__ResponseOptions_9;
  }
  get _XSRFStrategy_10():any {
    if ((this.__XSRFStrategy_10 == (null as any))) { (this.__XSRFStrategy_10 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_10;
  }
  get _XHRBackend_11():import10.XHRBackend {
    if ((this.__XHRBackend_11 == (null as any))) { (this.__XHRBackend_11 = new import10.XHRBackend(this._BrowserXhr_8,this._ResponseOptions_9,this._XSRFStrategy_10)); }
    return this.__XHRBackend_11;
  }
  get _RequestOptions_12():import11.BaseRequestOptions {
    if ((this.__RequestOptions_12 == (null as any))) { (this.__RequestOptions_12 = new import11.BaseRequestOptions()); }
    return this.__RequestOptions_12;
  }
  get _Http_13():any {
    if ((this.__Http_13 == (null as any))) { (this.__Http_13 = import5.httpFactory(this._XHRBackend_11,this._RequestOptions_12)); }
    return this.__Http_13;
  }
  get _UIModalService_14():import12.UIModalService {
    if ((this.__UIModalService_14 == (null as any))) { (this.__UIModalService_14 = new import12.UIModalService()); }
    return this.__UIModalService_14;
  }
  get _UIResourceCacheService_15():import13.UIResourceCacheService {
    if ((this.__UIResourceCacheService_15 == (null as any))) { (this.__UIResourceCacheService_15 = new import13.UIResourceCacheService()); }
    return this.__UIResourceCacheService_15;
  }
  get _TRANSLATIONS_FORMAT_16():any {
    if ((this.__TRANSLATIONS_FORMAT_16 == (null as any))) { (this.__TRANSLATIONS_FORMAT_16 = (null as any)); }
    return this.__TRANSLATIONS_FORMAT_16;
  }
  createInternal():import1.Angular2UIModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._HttpModule_3 = new import5.HttpModule();
    this._Angular2UIModule_4 = new import1.Angular2UIModule();
    return this._Angular2UIModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import1.Angular2UIModule)) { return this._Angular2UIModule_4; }
    if ((token === import15.LOCALE_ID)) { return this._LOCALE_ID_5; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import7.RadioControlRegistry)) { return this._RadioControlRegistry_7; }
    if ((token === import8.BrowserXhr)) { return this._BrowserXhr_8; }
    if ((token === import9.ResponseOptions)) { return this._ResponseOptions_9; }
    if ((token === import16.XSRFStrategy)) { return this._XSRFStrategy_10; }
    if ((token === import10.XHRBackend)) { return this._XHRBackend_11; }
    if ((token === import11.RequestOptions)) { return this._RequestOptions_12; }
    if ((token === import17.Http)) { return this._Http_13; }
    if ((token === import12.UIModalService)) { return this._UIModalService_14; }
    if ((token === import13.UIResourceCacheService)) { return this._UIResourceCacheService_15; }
    if ((token === import15.TRANSLATIONS_FORMAT)) { return this._TRANSLATIONS_FORMAT_16; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Angular2UIModuleNgFactory:import0.NgModuleFactory<import1.Angular2UIModule> = new import0.NgModuleFactory(Angular2UIModuleInjector,import1.Angular2UIModule);