/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from './ui-icon.component';
import * as import3 from '@angular/http';
import * as import4 from '../../services/ui-resource-cache.service';
const styles_UIIconComponent:any[] = ([] as any[]);
export const RenderType_UIIconComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIIconComponent,
  data: {}
}
);
function View_UIIconComponent_1(l:any):import0.ɵViewDefinition {
    return import0.ɵvid(0,[(l()(),import0.ɵeld(0,(null as any),(null as any),0,'img',([] as any[]),[
      [
        8,
        'src',
        4
      ]
      ,
      [
        8,
        'width',
        0
      ]
      ,
      [
        8,
        'height',
        0
      ]

    ]
  ,(null as any),(null as any),(null as any),(null as any)))],(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = co.imageSource;
    const currVal_1:any = co.widthText;
    const currVal_2:any = co.heightText;
    ck(v,0,0,currVal_0,currVal_1,currVal_2);
  });
}
export function View_UIIconComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_UIIconComponent_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(ck,v) => {
    var co:import2.UIIconComponent = v.component;
    const currVal_0:any = (co.imageSource != (null as any));
    ck(v,2,0,currVal_0);
  },(null as any));
}
function View_UIIconComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-icon',([] as any[]),(null as any),(null as any),(null as any),View_UIIconComponent_0,RenderType_UIIconComponent)),
    import0.ɵdid(57344,(null as any),0,import2.UIIconComponent,[
      import3.Http,
      import0.ElementRef,
      import4.UIResourceCacheService
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UIIconComponentNgFactory:import0.ComponentFactory<import2.UIIconComponent> = import0.ɵccf('ui-icon',import2.UIIconComponent,View_UIIconComponent_Host_0,{
  imageSource: 'img-src',
  svgSource: 'svg-src',
  width: 'width',
  height: 'height'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1pY29uL3VpLWljb24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktaWNvbi91aS1pY29uLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktaWNvbi91aS1pY29uLmNvbXBvbmVudC50cy5VSUljb25Db21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktaWNvbi91aS1pY29uLmNvbXBvbmVudC50cy5VSUljb25Db21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcblx0XHQ8aW1nICpuZ0lmPVwiaW1hZ2VTb3VyY2UgIT0gbnVsbFwiIFtzcmNdPVwiaW1hZ2VTb3VyY2VcIiBbd2lkdGhdPVwid2lkdGhUZXh0XCIgW2hlaWdodF09XCJoZWlnaHRUZXh0XCIgLz5cblx0IiwiPHVpLWljb24+PC91aS1pY29uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsyQkNDRTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztJQUFBO0dBQUE7O0lBQWlDO0lBQW9CO0lBQW9CO0lBQXpFLFNBQWlDLFVBQW9CLFVBQW9CLFNBQXpFOzs7OztJQURGO0lBQ0U7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFpRzs7OztJQUE1RjtJQUFMLFNBQUssU0FBTDs7Ozs7SUNERjtnQkFBQTs7OztJQUFBO0tBQUE7OztJQUFBOzs7Ozs7Ozs7In0=
