/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-addon.component';
const styles_UIAddonComponent:any[] = ([] as any[]);
export const RenderType_UIAddonComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIAddonComponent,
  data: {}
}
);
export function View_UIAddonComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',([] as any[]),[[
        2,
        'input-group-btn',
        (null as any)
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.UIAddonComponent = v.component;
    const currVal_0:any = (co.type == 'button');
    ck(v,1,0,currVal_0);
  });
}
function View_UIAddonComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-addon',([] as any[]),(null as any),(null as any),(null as any),View_UIAddonComponent_0,RenderType_UIAddonComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UIAddonComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UIAddonComponentNgFactory:import0.ComponentFactory<import1.UIAddonComponent> = import0.ɵccf('ui-addon',import1.UIAddonComponent,View_UIAddonComponent_Host_0,{type: 'type'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1pbnB1dC91aS1hZGRvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1pbnB1dC91aS1hZGRvbi5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWlucHV0L3VpLWFkZG9uLmNvbXBvbmVudC50cy5VSUFkZG9uQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWlucHV0L3VpLWFkZG9uLmNvbXBvbmVudC50cy5VSUFkZG9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG5cdFx0PHNwYW4gW2NsYXNzLmlucHV0LWdyb3VwLWJ0bl09XCJ0eXBlID09ICdidXR0b24nXCI+PG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50Pjwvc3Bhbj5cblx0IiwiPHVpLWFkZG9uPjwvdWktYWRkb24+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO01BQ0U7UUFBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO2dCQUFpRDtJQUFnQzs7OztJQUEzRTtJQUFOLFNBQU0sU0FBTjs7Ozs7SUNERjtnQkFBQTs7OzsifQ==
