/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-input-group.component';
const styles_UIInputGroupComponent:any[] = ([] as any[]);
export const RenderType_UIInputGroupComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIInputGroupComponent,
  data: {}
}
);
export function View_UIInputGroupComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'input-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(null as any));
}
function View_UIInputGroupComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-input-group',([] as any[]),(null as any),(null as any),(null as any),View_UIInputGroupComponent_0,RenderType_UIInputGroupComponent)),
    import0.ɵdid(24576,(null as any),0,import1.UIInputGroupComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UIInputGroupComponentNgFactory:import0.ComponentFactory<import1.UIInputGroupComponent> = import0.ɵccf('ui-input-group',import1.UIInputGroupComponent,View_UIInputGroupComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1pbnB1dC91aS1pbnB1dC1ncm91cC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1pbnB1dC91aS1pbnB1dC1ncm91cC5jb21wb25lbnQudHMiLCJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWlucHV0L3VpLWlucHV0LWdyb3VwLmNvbXBvbmVudC50cy5VSUlucHV0R3JvdXBDb21wb25lbnQuaHRtbCIsIm5nOi8vL0Q6L0NvZGUvYW5ndWxhcjItdWkvc3JjL2NvbXBvbmVudHMvdWktaW5wdXQvdWktaW5wdXQtZ3JvdXAuY29tcG9uZW50LnRzLlVJSW5wdXRHcm91cENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuXHRcdDxkaXYgY2xhc3M9XCJpbnB1dC1ncm91cFwiPlxuXHRcdFx0PG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuXHRcdDwvZGl2PlxuXHQiLCI8dWktaW5wdXQtZ3JvdXA+PC91aS1pbnB1dC1ncm91cD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDRTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXlCO2dCQUN4QjtJQUF5QjtJQUNwQjs7Ozs7O0lDSFI7Z0JBQUE7Ozs7In0=
