/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './ui-column.component';
const styles_UIColumnComponent:any[] = ([] as any[]);
export const RenderType_UIColumnComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UIColumnComponent,
  data: {}
}
);
export function View_UIColumnComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n		'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',([] as any[]),[[
        8,
        'className',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n			'])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n		'])),
    (l()(),import0.ɵted((null as any),['\n	']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.UIColumnComponent = v.component;
    const currVal_0:any = co.classBinding;
    ck(v,1,0,currVal_0);
  });
}
function View_UIColumnComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ui-column',([] as any[]),(null as any),(null as any),(null as any),View_UIColumnComponent_0,RenderType_UIColumnComponent)),
    import0.ɵdid(57344,(null as any),0,import1.UIColumnComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UIColumnComponentNgFactory:import0.ComponentFactory<import1.UIColumnComponent> = import0.ɵccf('ui-column',import1.UIColumnComponent,View_UIColumnComponent_Host_0,{
  extraSmallWidth: 'xs-width',
  smallWidth: 'sm-width',
  mediumWidth: 'md-width',
  largeWidth: 'lg-width',
  extraLargeWidth: 'xl-width'
}
,{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jb2x1bW4vdWktY29sdW1uLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9Db2RlL2FuZ3VsYXIyLXVpL3NyYy9jb21wb25lbnRzL3VpLWNvbHVtbi91aS1jb2x1bW4uY29tcG9uZW50LnRzIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jb2x1bW4vdWktY29sdW1uLmNvbXBvbmVudC50cy5VSUNvbHVtbkNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovQ29kZS9hbmd1bGFyMi11aS9zcmMvY29tcG9uZW50cy91aS1jb2x1bW4vdWktY29sdW1uLmNvbXBvbmVudC50cy5VSUNvbHVtbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuXHRcdDxkaXYgW2NsYXNzXT1cImNsYXNzQmluZGluZ1wiPlxuXHRcdFx0PG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuXHRcdDwvZGl2PlxuXHQiLCI8dWktY29sdW1uPjwvdWktY29sdW1uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNFO1FBQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUE0QjtnQkFDM0I7SUFBeUI7SUFDcEI7Ozs7SUFGRDtJQUFMLFNBQUssU0FBTDs7Ozs7SUNERjtnQkFBQTs7O0lBQUE7Ozs7Ozs7Ozs7In0=
