/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './ui-typeahead.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/forms/src/directives/default_value_accessor';
import * as import11 from '@angular/forms/src/directives/ng_model';
import * as import12 from '@angular/forms/src/directives/ng_control_status';
import * as import13 from '@angular/common/src/directives/ng_for';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/forms/src/directives/control_value_accessor';
import * as import18 from '@angular/forms/src/directives/ng_control';
var renderType_UITypeaheadComponent_Host:import0.RenderComponentType = (null as any);
class _View_UITypeaheadComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UITypeaheadComponent_0_4:import3.UITypeaheadComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UITypeaheadComponent_Host0,renderType_UITypeaheadComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ui-typeahead',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UITypeaheadComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UITypeaheadComponent_0_4 = new import3.UITypeaheadComponent();
    this._appEl_0.initComponent(this._UITypeaheadComponent_0_4,[],compView_0);
    compView_0.create(this._UITypeaheadComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UITypeaheadComponent) && (0 === requestNodeIndex))) { return this._UITypeaheadComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._UITypeaheadComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UITypeaheadComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UITypeaheadComponent_Host === (null as any))) { (renderType_UITypeaheadComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_UITypeaheadComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UITypeaheadComponentNgFactory:import9.ComponentFactory<import3.UITypeaheadComponent> = new import9.ComponentFactory<import3.UITypeaheadComponent>('ui-typeahead',viewFactory_UITypeaheadComponent_Host0,import3.UITypeaheadComponent);
const styles_UITypeaheadComponent:any[] = [];
var renderType_UITypeaheadComponent:import0.RenderComponentType = (null as any);
class _View_UITypeaheadComponent0 extends import1.AppView<import3.UITypeaheadComponent> {
  _text_0:any;
  _el_1:any;
  _DefaultValueAccessor_1_3:import10.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_1_4:any[];
  _NgModel_1_5:import11.NgModel;
  _NgControl_1_6:any;
  _NgControlStatus_1_7:import12.NgControlStatus;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _TemplateRef_5_5:any;
  _NgFor_5_6:import13.NgFor;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UITypeaheadComponent0,renderType_UITypeaheadComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n		',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'input',(null as any));
    this.renderer.setElementAttribute(this._el_1,'autocomplete','off');
    this.renderer.setElementAttribute(this._el_1,'class','form-control');
    this._DefaultValueAccessor_1_3 = new import10.DefaultValueAccessor(this.renderer,new import14.ElementRef(this._el_1));
    this._NG_VALUE_ACCESSOR_1_4 = [this._DefaultValueAccessor_1_3];
    this._NgModel_1_5 = new import11.NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_1_4);
    this._NgControl_1_6 = this._NgModel_1_5;
    this._NgControlStatus_1_7 = new import12.NgControlStatus(this._NgControl_1_6);
    this._text_2 = this.renderer.createText(parentRenderNode,'\n		',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','dropdown-menu  search-results');
    this._text_4 = this.renderer.createText(this._el_3,'\n        	',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._appEl_5 = new import2.AppElement(5,3,this,this._anchor_5);
    this._TemplateRef_5_5 = new import15.TemplateRef_(this._appEl_5,viewFactory_UITypeaheadComponent1);
    this._NgFor_5_6 = new import13.NgFor(this._appEl_5.vcRef,this._TemplateRef_5_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_6 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n	',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'ngModelChange',this.eventHandler(this._handle_ngModelChange_1_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_1,'input',this.eventHandler(this._handle_input_1_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_1,'blur',this.eventHandler(this._handle_blur_1_2.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    const subscription_0:any = this._NgModel_1_5.update.subscribe(this.eventHandler(this._handle_ngModelChange_1_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._text_7
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.DefaultValueAccessor) && (1 === requestNodeIndex))) { return this._DefaultValueAccessor_1_3; }
    if (((token === import17.NG_VALUE_ACCESSOR) && (1 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_1_4; }
    if (((token === import11.NgModel) && (1 === requestNodeIndex))) { return this._NgModel_1_5; }
    if (((token === import18.NgControl) && (1 === requestNodeIndex))) { return this._NgControl_1_6; }
    if (((token === import12.NgControlStatus) && (1 === requestNodeIndex))) { return this._NgControlStatus_1_7; }
    if (((token === import15.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import13.NgFor) && (5 === requestNodeIndex))) { return this._NgFor_5_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_3:any = this.context.searchText;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgModel_1_5.model = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._NgModel_1_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_10:any = this.context.searchResults;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_5_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_5_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_5_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = this._NgControlStatus_1_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_1,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_1_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_1,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_1_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_1,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_1_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_1,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_1_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_1,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_1_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_1,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_1_5.ngOnDestroy();
  }
  private _handle_ngModelChange_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.searchText = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_1_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_1_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_1_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_1_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UITypeaheadComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UITypeaheadComponent> {
  if ((renderType_UITypeaheadComponent === (null as any))) { (renderType_UITypeaheadComponent = viewUtils.createRenderComponentType('D:/Code/angular2-ui/src/components/ui-typeahead/ui-typeahead.component.ts class UITypeaheadComponent - inline template',0,import8.ViewEncapsulation.None,styles_UITypeaheadComponent,{})); }
  return new _View_UITypeaheadComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UITypeaheadComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UITypeaheadComponent1,renderType_UITypeaheadComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'a',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','dropdown-item');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onClick(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_UITypeaheadComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UITypeaheadComponent1(viewUtils,parentInjector,declarationEl);
}